project:
  type: website
  output-dir: docs


website:
  title: "Alexander Meehan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html: 
  theme:
    - cosmo
    - custom.scss
      light: flatly
      dark: darkly
      fontsize: 1.1em
      linestretch: 1.7
    css: styles.css
    toc: true



