project:
  type: website
  output-dir: docs

website:
  title: "Alexander Meehan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: research_proposal_field_exp.qmd
        text: Research Proposal

format:
  html:
    theme:
      light:
        - flatly
        - styles.scss
      dark:
        - darkly
        - styles.scss